#%RAML 0.8
title: User Management API
version: 1.0
#baseUri: https://localhost:8091/api/busregervation/user
baseUri: https://mocksvc.mulesoft.com/mocks/651f6fd6-e5ee-4534-b5d7-78b742e9a99c/api/busregervation/user
/registeruser:
  post:
    description: Post user details in Request parameters 
    #headers: 
    queryParameters: 
      userfirstname:
        description: User First name
        type: string
        required: true
        example: John
      usermiddlename:
        description: User middle name
        type: string
        required: false
        example: Dave
      userlastname:
        description: User Last name
        type: string
        required: true
        example: Mark
      userage:
        description: User Age
        type: integer
        required: true
        example: 26
      userdob:
        description: User Date of birth
        type: string
        required: true
        example: 03/22/1985
      phoneNumber:
        description: Phone Number
        type: string
        required: true
        example: 9900123450
      email:
        description: Email
        type: string
        required: true
        example: abc@abcsdsd.com
    responses: 
      201:
        body: 
          application/json:
            example: |
              {
                "data": {
                    "results": "user created",
                     "userid": "121313"
                                     
                  },
                 
              "success":true,
              "status": 201
              }
/getuserdetails:
    displayName: Retrieves user details for the given userid
    get:
      queryParameters: 
        userid:
          type: string
          required: true
          example: johndave
      responses: 
        201:
          body: 
            application/json:
              example: |
                {
                "userdetails": {
                  "userfirstname" : "John",
                  "usermiddlename" : "Dave",
                  "userlastname" : "Mark",
                  "userage" : "29",
                  "userdob" : "03/22/1985",
                  "useremail" : "abc@abcsdsd.com",
                  "userphone" : "9900123450"
                },
                "success":true,
                "status": 201
                }
    
              
