#%RAML 0.8
title: Reservation system API
version: 1.0
#baseUri: https://localhost:8091/api/busregervation/user

schemas: 
   - userdata: !include schema/userdata.json
   - search: !include schema/searchservice.json

/user/registration:
  post:
    description: Post user details in Request parameters 
   
    body: 
      application/json:
        schema: userdata
    responses: 
      200:
        body: 
          application/json:
            example: !include example/reguser_resp.json
 
/user/account/{userid}:
   
    displayName: Retrieves user details for the given userid
    get:
      responses: 
        200:
          body: 
            application/json:
              schema: userdata
              example: !include example/userdata_sample.json

/user/security/authentication:
  displayName: authenticates user by userid and password
  get:
    queryParameters: 
      userid:
        type: string
        required: true
        example: johndave
      password:
        type: string
        required: true
        example: password
    responses: 
      200:
        body: 
          application/json:
            example: |
              {
                "resut": "true"
              }
/search/services:
  get:
    queryParameters: 
      origin:
        type: string
        description: start point of the journey
        example: NYC for Newyork City
      destination:
        type: string
        description: end point of the journey
        example: BOS for Boston
      departureDate:
        type: date
        description: start date of the journey
        example: 2017-12-23
      arrivalDate:
        type: date
        description: end date of the journey if selected round trip
        example: 2017-12-24
    responses: 
      200:
        
        body: 
          application/json:
            schema: search
            example: !include example/search_data.json